export const colorByType = {
        
    normal:"bg-[#BCBCAC]",
    fighting:"bg-[#BC5442]",
    flying:"bg-[#669AFF]",
    poison:"bg-[#AB549A]",
    ground:"bg-[#DEBC54]",
    rock:"bg-[#BCAC66]",
    bug:"bg-[#ABBC1C]",
    ghost:"bg-[#6666BC]",
    steel:"bg-[#ABACBC]",
    fire:"bg-[#FF421C]",
    water:"bg-[#2F9AFF]",
    grass:"bg-[#78CD54]",
    electric:"bg-[#FFCD30]",
    psychic:"bg-[#FF549A]",
    ice:"bg-[#78DEFF]",
    dragon:"bg-[#7866EF]",
    dark:"bg-[#785442]",
    fairy:"bg-[#FFACFF]",
    unknown:"",
    shadow:"",
}

export const colorBorderByType = {
        
    normal:"border-[#BCBCAC]",
    fighting:"border-[#BC5442]",
    flying:"border-[#669AFF]",
    poison:"border-[#AB549A]",
    ground:"border-[#DEBC54]",
    rock:"border-[#BCAC66]",
    bug:"border-[#ABBC1C]",
    ghost:"border-[#6666BC]",
    steel:"border-[#ABACBC]",
    fire:"border-[#FF421C]",
    water:"border-[#2F9AFF]",
    grass:"border-[#78CD54]",
    electric:"border-[#FFCD30]",
    psychic:"border-[#FF549A]",
    ice:"border-[#78DEFF]",
    dragon:"border-[#7866EF]",
    dark:"border-[#785442]",
    fairy:"border-[#FFACFF]",
    unknown:"",
    shadow:"",
}
